config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"
  devise_for :users
  post '/plaids/plaid_link_token'
  resources :businesses do 
    get 'plaids_authenticated'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ApplicationRecord
  has_many :users, through: :tenants
  has_many :tenants, dependent: :destroy
end

app/models/customer.rb
class Customer < ApplicationRecord
  
end

app/models/tenant.rb
class Tenant < ApplicationRecord
  belongs_to :user
  belongs_to :business
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :businesses, through: :tenants
  has_many :tenants, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    @businesses = Business.all
  end

  def new
    @business = Business.new
  end

  def create
    @business = Business.new(business_params)

    if @business.save
      redirect_to business_plaids_authenticated_path(@business.id)
    else
      render :new
    end
  end

  private

  def set_business
    @business = business.find(params[:id])
  end

  def business_params
    params.require(:business).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/businesses/index.html.erb
<div class="container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Title</th>
      </tr>
    </thead>
    <tbody>
      <% @businesses.each do |business| %>
        <tr>
          <td><%= business.title %></td>
          <td> <button id="linkButton">Open Link - Institution Select</button> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= link_to 'New business', new_business_path %>

app/views/businesses/new.html.erb
<%= form_with(model: @business, local: true) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/businesses/plaids_authenticated.html.erb
<script src="https://cdn.plaid.com/link/v2/stable/link-initialize.js"></script>
<script>
    var linkHandler = Plaid.create({
      token: 'link-sandbox-a98ec61a-b81c-4253-82d8-1bbef8457495',
      onLoad: function() {
      },
      onSuccess: function(public_token, metadata) {
        console.log('Public Token: ' + public_token);
      },
      onExit: function(err, metadata) {
        if (err != null) {
          console.log(err);
        }
      },
    });
    linkHandler.open();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scroll</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Webinari Payments</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li>
        <a class="nav-link" href="#">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown link
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li style= "margin-left: 1150px;">
      <% if current_user.present? %>
        <%= link_to 'Logout' , destroy_user_session_path, method: :delete, class: "nav-link" %>
      <% else %>
      </li>
      <li>
        <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
      </li>
      <li>
        <%= link_to 'Log In', new_user_session_path, class: "nav-link" %>
      <% end %>
      </li>
    </ul>
  </div>
</nav>

<button id="linkButton">Open Link - Institution Select</button>
<script src="https://cdn.plaid.com/link/v2/stable/link-initialize.js"></script>
<script>
    var linkHandler = Plaid.create({
      token: 'link-development-2e6a0031-4b01-4202-8192-27f958d79649',
      onLoad: function() {
      },
      onSuccess: function(public_token, metadata) {
      },
      onExit: function(err, metadata) {
      },
    });

  document.getElementById('linkButton').onclick = function() {
    linkHandler.open();
  };
</script>